### ISSUE TITLE
nversary may send multiple messages per person or skip sending

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nversary#39]
Multiple messages may be sent in following case.
- There are more than 1 person to congratulate
- Message is sent successfully for some persons, but sending for later persons fails. E.g Slack API says 429 Too many requests
- nversary Lambda gets retried a bit later and manages this time to send all the messages successfully

Way to fix:
- Store state about successfully sent messages to somewhere (e.g. S3). Check before sending if those have already been sent.

**Comment by gmokki** [comment]
I would do initially a simpler fix. Add 1 second sleep between posting messages since slack rate limits https://api.slack.com/docs/rate-limits say that apps can send max 1 message per second to one channel.

**Comment by jsyrjala** [comment]
If sending fails, then Lambda retries up to three times. If sending fails also on last attempt, then some notification can be missing

https://nitorgroup.slack.com/archives/C043Y527E/p1701870476938129

**Comment by okko** [comment]
Alternative fix: push messages to an SQS queue and have another Lambda handler attqched to that queue to make Slack reqs, with sleep after each msg. The queue automatically retries if the function fails.

**Comment by jsyrjala** [comment]
Added bunch of delays. Added also caching for listing Slack users since it has separate rate limiting rules.
